// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.warm.game.protocol.room;

public final class RoomMsgProto {
  private RoomMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface sucessMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string battle_flag = 1;
    /**
     * <code>optional string battle_flag = 1;</code>
     */
    boolean hasBattleFlag();
    /**
     * <code>optional string battle_flag = 1;</code>
     */
    java.lang.String getBattleFlag();
    /**
     * <code>optional string battle_flag = 1;</code>
     */
    com.google.protobuf.ByteString
        getBattleFlagBytes();
  }
  /**
   * Protobuf type {@code sucessMsg}
   */
  public static final class sucessMsg extends
      com.google.protobuf.GeneratedMessage
      implements sucessMsgOrBuilder {
    // Use sucessMsg.newBuilder() to construct.
    private sucessMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private sucessMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final sucessMsg defaultInstance;
    public static sucessMsg getDefaultInstance() {
      return defaultInstance;
    }

    public sucessMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private sucessMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              battleFlag_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.warm.game.protocol.room.RoomMsgProto.internal_static_sucessMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.warm.game.protocol.room.RoomMsgProto.internal_static_sucessMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.warm.game.protocol.room.RoomMsgProto.sucessMsg.class, com.warm.game.protocol.room.RoomMsgProto.sucessMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<sucessMsg> PARSER =
        new com.google.protobuf.AbstractParser<sucessMsg>() {
      public sucessMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new sucessMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<sucessMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string battle_flag = 1;
    public static final int BATTLE_FLAG_FIELD_NUMBER = 1;
    private java.lang.Object battleFlag_;
    /**
     * <code>optional string battle_flag = 1;</code>
     */
    public boolean hasBattleFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string battle_flag = 1;</code>
     */
    public java.lang.String getBattleFlag() {
      java.lang.Object ref = battleFlag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          battleFlag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string battle_flag = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBattleFlagBytes() {
      java.lang.Object ref = battleFlag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        battleFlag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      battleFlag_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBattleFlagBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBattleFlagBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.warm.game.protocol.room.RoomMsgProto.sucessMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.warm.game.protocol.room.RoomMsgProto.sucessMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sucessMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.warm.game.protocol.room.RoomMsgProto.sucessMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.warm.game.protocol.room.RoomMsgProto.internal_static_sucessMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.warm.game.protocol.room.RoomMsgProto.internal_static_sucessMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.warm.game.protocol.room.RoomMsgProto.sucessMsg.class, com.warm.game.protocol.room.RoomMsgProto.sucessMsg.Builder.class);
      }

      // Construct using com.warm.game.protocol.room.RoomMsgProto.sucessMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        battleFlag_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.warm.game.protocol.room.RoomMsgProto.internal_static_sucessMsg_descriptor;
      }

      public com.warm.game.protocol.room.RoomMsgProto.sucessMsg getDefaultInstanceForType() {
        return com.warm.game.protocol.room.RoomMsgProto.sucessMsg.getDefaultInstance();
      }

      public com.warm.game.protocol.room.RoomMsgProto.sucessMsg build() {
        com.warm.game.protocol.room.RoomMsgProto.sucessMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.warm.game.protocol.room.RoomMsgProto.sucessMsg buildPartial() {
        com.warm.game.protocol.room.RoomMsgProto.sucessMsg result = new com.warm.game.protocol.room.RoomMsgProto.sucessMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.battleFlag_ = battleFlag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.warm.game.protocol.room.RoomMsgProto.sucessMsg) {
          return mergeFrom((com.warm.game.protocol.room.RoomMsgProto.sucessMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.warm.game.protocol.room.RoomMsgProto.sucessMsg other) {
        if (other == com.warm.game.protocol.room.RoomMsgProto.sucessMsg.getDefaultInstance()) return this;
        if (other.hasBattleFlag()) {
          bitField0_ |= 0x00000001;
          battleFlag_ = other.battleFlag_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.warm.game.protocol.room.RoomMsgProto.sucessMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.warm.game.protocol.room.RoomMsgProto.sucessMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string battle_flag = 1;
      private java.lang.Object battleFlag_ = "";
      /**
       * <code>optional string battle_flag = 1;</code>
       */
      public boolean hasBattleFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string battle_flag = 1;</code>
       */
      public java.lang.String getBattleFlag() {
        java.lang.Object ref = battleFlag_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          battleFlag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string battle_flag = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBattleFlagBytes() {
        java.lang.Object ref = battleFlag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          battleFlag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string battle_flag = 1;</code>
       */
      public Builder setBattleFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        battleFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string battle_flag = 1;</code>
       */
      public Builder clearBattleFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        battleFlag_ = getDefaultInstance().getBattleFlag();
        onChanged();
        return this;
      }
      /**
       * <code>optional string battle_flag = 1;</code>
       */
      public Builder setBattleFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        battleFlag_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sucessMsg)
    }

    static {
      defaultInstance = new sucessMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sucessMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sucessMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sucessMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nroom.proto\" \n\tsucessMsg\022\023\n\013battle_flag" +
      "\030\001 \001(\tB+\n\033com.warm.game.protocol.roomB\014R" +
      "oomMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sucessMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sucessMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sucessMsg_descriptor,
              new java.lang.String[] { "BattleFlag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
